### PR TITLE
Use non-deprecated `Sink` class

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
My build fails with

```
[ERROR] src/jenkinsci/maven-jellydoc-plugin/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java:[72,7] error: JellydocMojo is not abstract and does not override abstract method generate(Sink,Locale) in MavenReport
```

Note that I am using 

https://github.com/jenkinsci/maven-jellydoc-plugin/blob/master/maven-jellydoc-plugin/pom.xml#L137-L147

```
[INFO] +- org.apache.maven.reporting:maven-reporting-impl:jar:3.2.0:compile
[INFO] |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.1.1:compile
```

@michael-osipov Is there a way for me to make Maven Jellydoc Plugin forward compatible with Maven Site Plugin 4, while continuing to have a primary target (and actual usage) of Maven Site Plugin 3?

**Comment by basil** [comment]
Happy New Year @michael-o. Is there a way for me to make Maven Jellydoc Plugin forward compatible with Maven Site Plugin 4, while continuing to have a primary target (and actual usage) of Maven Site Plugin 3?

**Comment by michael-o** [comment]
Why do you use impl if you don't implement AbstractMavenReport? In your case you should implement similarly I did with Maven Javadoc Plugin, the you don't need impl since you have a hybrid plugin.

**Comment by basil** [comment]
> Why do you use impl

I did a case-insensitive search for the string `impl` in the two files that use the deprecated `Sink` class (`JellydocMojo.java` and `ReferenceRenderer.java`) and did not find any results. So as far as I can tell I am not using impl. So I do not understand what you are saying.

**Comment by michael-o** [comment]
> > Why do you use impl
> 
> I did a case-insensitive search for the string `impl` in the two files that use the deprecated `Sink` class (`JellydocMojo.java` and `ReferenceRenderer.java`) and did not find any results. So as far as I can tell I am not using impl. So I do not understand what you are saying.

But you depend on it. You can safely remove it first

**Comment by basil** [comment]
> But you depend on it.

Here "it" is a pronoun whose antecedent is "impl". I searched `pom.xml` for the string "impl" but did not find it. So as far as I can tell I do not depend on impl. So I do not understand what you are saying.

**Comment by michael-o** [comment]
https://github.com/jenkinsci/maven-jellydoc-plugin/blob/b1ee32d80774157c4335871185c3bfe7a7918be1/maven-jellydoc-plugin/pom.xml#L137-L147

**Comment by basil** [comment]
Thanks Michael, I had missed that in my search because I was only looking in the root directory. I tried doing what you suggested via

```xml
diff --git a/maven-jellydoc-plugin/pom.xml b/maven-jellydoc-plugin/pom.xml
index 9d65729..0613a26 100644
--- a/maven-jellydoc-plugin/pom.xml
+++ b/maven-jellydoc-plugin/pom.xml
@@ -136,14 +136,8 @@
     </dependency>
     <dependency>
       <groupId>org.apache.maven.reporting</groupId>
-      <artifactId>maven-reporting-impl</artifactId>
-      <version>3.2.0</version>
-      <exclusions>
-        <exclusion>
-          <groupId>dom4j</groupId>
-          <artifactId>dom4j</artifactId>
-        </exclusion>
-      </exclusions>
+      <artifactId>maven-reporting-api</artifactId>
+      <version>3.1.1</version>
     </dependency>
```

But it turns out that something in this plugin depends on `maven-reporting-impl`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project maven-jellydoc-plugin: Compilation failure: Compilation failure: 
[ERROR] /home/basil/src/jenkinsci/maven-jellydoc-plugin/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java:[18,33] error: cannot find symbol
[ERROR]   symbol:   class AbstractMavenReportRenderer
[ERROR]   location: package org.apache.maven.reporting
[ERROR] /home/basil/src/jenkinsci/maven-jellydoc-plugin/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java:[44,39] error: cannot find symbol
[ERROR]   symbol: class AbstractMavenReportRenderer
[ERROR] -> [Help 1]
```

Since I didn't write this code and have no experience writing Maven plugins, I have no idea what `ReferenceRenderer` is doing or why it needs `AbstractMavenReportRenderer` from `maven-reporting-impl`.

> Why do you use impl if you don't implement AbstractMavenReport?

Apparently because `ReferenceRenderer` needs it.

> You can safely remove it first

Apparently not, as described above.

In any case I do not see how switching the dependency from `maven-reporting-impl` to `maven-reporting-api` has anything to do with my question about make Maven Jellydoc Plugin forward compatible with Maven Site Plugin 4, while continuing to have a primary target (and actual usage) of Maven Site Plugin 3.

**Comment by michael-o** [comment]
Let me check this later today and get back to you

**Comment by michael-o** [comment]
Looking into now. First of all, I would recomment to resolve this problem:
```
[INFO] --- maven-dependency-plugin:3.3.0:analyze (default-cli) @ maven-jellydoc-plugin ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.apache.maven.doxia:doxia-sink-api:jar:1.11.1:compile
[WARNING]    org.codehaus.plexus:plexus-utils:jar:3.5.0:compile
[WARNING]    com.sun.xml.txw2:txw2:jar:20110809:compile
[WARNING]    xml-apis:xml-apis:jar:1.3.03:compile
[WARNING]    org.apache.maven.reporting:maven-reporting-api:jar:3.1.1:compile
[WARNING] Unused declared dependencies found:
[WARNING]    jaxen:jaxen:jar:1.2.0:compile
[WARNING]    org.apache.maven:maven-model:jar:3.8.7:provided
```

**Comment by michael-o** [comment]
Here it is, incomplete because generate(3 arg) requires some polish, but it compiles:

```patch
osipovmi@deblndw011x:~/var/Projekte/maven-jellydoc-plugin (master *>)
$ git diff -U0
diff --git a/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java b/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java
index 12aa447..7ccd18f 100644
--- a/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java
+++ b/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java
@@ -32 +32 @@ import org.apache.maven.project.MavenProjectHelper;
-import org.apache.maven.reporting.MavenReport;
+import org.apache.maven.reporting.MavenMultiPageReport;
@@ -41 +41,4 @@ import org.apache.tools.ant.types.Path;
-import org.codehaus.doxia.sink.Sink;
+import org.apache.maven.doxia.sink.Sink;
+import org.apache.maven.doxia.sink.SinkFactory;
+import org.apache.maven.doxia.siterenderer.RenderingContext;
+import org.apache.maven.doxia.siterenderer.sink.SiteRendererSink;
@@ -70 +73 @@ import java.util.Locale;
-public class JellydocMojo extends AbstractMojo implements MavenReport {
+public class JellydocMojo extends AbstractMojo implements MavenMultiPageReport {
@@ -208,0 +212,4 @@ public class JellydocMojo extends AbstractMojo implements MavenReport {
+    public void generate(org.codehaus.doxia.sink.Sink sink, Locale locale) throws MavenReportException {
+        generate(sink, null, locale);
+    }
+
@@ -209,0 +217,5 @@ public class JellydocMojo extends AbstractMojo implements MavenReport {
+        generate(sink, null, locale);
+    }
+
+    @Override
+    public void generate(Sink sink, SinkFactory sinkFactory, Locale locale) throws MavenReportException {
diff --git a/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java b/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java
index 6a532f4..24262fd 100644
--- a/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java
+++ b/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java
@@ -23 +23 @@ import org.dom4j.io.SAXReader;
-import org.codehaus.doxia.sink.Sink;
+import org.apache.maven.doxia.sink.Sink;
```

**Comment by basil** [comment]
Brilliant! Thanks Michael, the pointer to `MavenMultiPageReport` was all I needed. Now the interfaces and compatibility requirements all make sense.

**Pull request merged**
